name: 'publish'

on:
    push:
        branches:
            - main

    workflow_dispatch:

env:
    TAG_NAME: v1.0.0
    RELEASE_NAME: 'vs-code-terminal_v1.0.0'
    DEB_FILE_NAME: 'vs-code-terminal_v1.0.0.deb'
    RPM_FILE_NAME: 'vs-code-terminal_v1.0.0.rpm'
    APPIMAGE_FILE_NAME: 'vs-code-terminal_v1.0.0.AppImage'
    EXE_FILE_NAME: 'vs-code-terminal_v1.0.0.exe'


jobs:
    publish-linux:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            # - name: Setup GitHub CLI
            #   run: |
            #       type -p curl >/dev/null || sudo apt install curl -y
            #       curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            #       sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            #       echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | \
            #         sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            #       sudo apt update
            #       sudo apt install gh -y


            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

            - name: Install Tauri Linux dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y \
                  libgtk-3-dev \
                  libwebkit2gtk-4.1-dev \
                  libayatana-appindicator3-dev \
                  librsvg2-dev \
                  patchelf \
                  desktop-file-utils \
                  libfuse2 \
                  webkit2gtk-driver \
                  xvfb

            - name: Install dependencies
              run: npm install

            - name: Build app bundle
              run: |
                  npm run tauri build

            # - name: Get Node project version
            #   id: package-version
            #   uses: martinbeentjes/npm-get-version-action@v1.3.1

            - name: Rename bundle
              run: |
                  mv ./src-tauri/target/release/bundle/deb/vsc-terminal_0.1.0_amd64.deb ./src-tauri/target/release/bundle/deb/${{ env.DEB_FILE_NAME }}
                  mv ./src-tauri/target/release/bundle/rpm/vsc-terminal-0.1.0-1.x86_64.rpm ./src-tauri/target/release/bundle/rpm/${{ env.RPM_FILE_NAME }}
                  mv ./src-tauri/target/release/bundle/appimage/vsc-terminal_0.1.0_amd64.AppImage ./src-tauri/target/release/bundle/appimage/${{ env.APPIMAGE_FILE_NAME }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: linux-build
                  path: |
                      ./src-tauri/target/release/bundle/deb/${{ env.DEB_FILE_NAME }}
                      ./src-tauri/target/release/bundle/rpm/${{ env.RPM_FILE_NAME }}
                      ./src-tauri/target/release/bundle/appimage/${{ env.APPIMAGE_FILE_NAME }}

    publish-windows:
        runs-on: windows-latest

        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            # - name: Setup GitHub CLI
            #   run: |
            #       choco install gh --version=2.83.2 -y
            #   shell: powershell

            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  cache: 'npm'

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: x86_64-pc-windows-msvc

            - name: Install Visual Studio Build Tools
              uses: microsoft/setup-msbuild@v1

            - name: Install Rust target
              run: rustup target add x86_64-pc-windows-msvc

            # - name: Install Tauri CLI
            #   run: cargo install tauri-cli

            - name: Install dependencies
              run: npm install

            - name: Build app bundle
              run: npm run tauri build -- --target x86_64-pc-windows-msvc

            - name: Rename exe file
              shell: cmd
              run: |
                  ren "src-tauri\target\x86_64-pc-windows-msvc\release\bundle\nsis\vsc-terminal_0.1.0_x64-setup.exe" "%EXE_FILE_NAME%"

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: windows-build
                  path: src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/${{ env.EXE_FILE_NAME }}

   
    release:
        runs-on: ubuntu-latest
        needs: [publish-linux, publish-windows]
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts

            - name: List files
              run: ls -R artifacts

            - name: Create Tag
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git tag ${{ env.TAG_NAME }}
                  git push origin ${{ env.TAG_NAME }}

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  draft: false
                  name: ${{ env.RELEASE_NAME }}
                  tag_name: ${{ env.TAG_NAME }}
                  generate_release_notes: true
                  files: |
                      artifacts/linux-build/deb/${{ env.DEB_FILE_NAME }}
                      artifacts/linux-build/rpm/${{ env.RPM_FILE_NAME }}
                      artifacts/linux-build/appimage/${{ env.APPIMAGE_FILE_NAME }}
                      artifacts/windows-build/${{ env.EXE_FILE_NAME }}
