name: 'publish'

on:
    push:
        branches:
            - main

    workflow_dispatch:

env:
    TAG_NAME: v1.0.0
    RELEASE_NAME: 'vs-code-terminal_v1.0.0'
    DEB_FILE_NAME: 'vs-code-terminal_v1.0.0.deb'
    RPM_FILE_NAME: 'vs-code-terminal_v1.0.0.deb'
    APPIMAGE_FILE_NAME: 'vs-code-terminal_v1.0.0.deb'


jobs:
    publish-linux:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            # - name: Setup GitHub CLI
            #   run: |
            #       type -p curl >/dev/null || sudo apt install curl -y
            #       curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            #       sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            #       echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | \
            #         sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            #       sudo apt update
            #       sudo apt install gh -y


            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

            - name: Install Tauri Linux dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y \
                  libgtk-3-dev \
                  libwebkit2gtk-4.1-dev \
                  libayatana-appindicator3-dev \
                  librsvg2-dev \
                  patchelf \
                  desktop-file-utils \
                  libfuse2 \
                  webkit2gtk-driver \
                  xvfb

            - name: Install dependencies
              run: npm install

            - name: Build app bundle
              run: |
                  npm run tauri build

            # - name: Get Node project version
            #   id: package-version
            #   uses: martinbeentjes/npm-get-version-action@v1.3.1

            - name: Rename bundle
              run: |
                  mv ./src-tauri/target/release/bundle/deb/vsc-terminal_0.1.0_amd64.deb ./src-tauri/target/release/bundle/deb/${{ env.DEB_FILE_NAME }}
                  mv ./src-tauri/target/release/bundle/rpm/vsc-terminal-0.1.0-1.x86_64.rpm ./src-tauri/target/release/bundle/rpm/${{ env.RPM_FILE_NAME }}
                  mv ./src-tauri/target/release/bundle/appimage/vsc-terminal_0.1.0_amd64.AppImage ./src-tauri/target/release/bundle/appimage/${{ env.APPIMAGE_FILE_NAME }}

            - name: Remove old tag if exists
              run: |
                  if git ls-remote --tags origin | grep -q "refs/tags/${{ env.TAG_NAME }}"; then
                    echo "Deleting old tag..."
                    git push origin :refs/tags/"${{ env.TAG_NAME }}"
                  else
                    echo "No old tag found."
                  fi

            - name: Create Tag
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git tag ${{ env.TAG_NAME }}
                  git push origin ${{ env.TAG_NAME }}

            - name: Remove old release if exists
              run: |
                  if gh release view ${{ env.RELEASE_NAME }} &>/dev/null; then
                    echo "Deleting old release..."
                    gh release delete ${{ env.RELEASE_NAME }} -y
                  else
                    echo "No old release found."
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish
              uses: softprops/action-gh-release@v1
              with:
                  draft: false
                  name: App v${{ steps.package-version.outputs.current-version}}
                  tag_name: v${{ steps.package-version.outputs.current-version}}
                  generate_release_notes: true
                  files: |
                      ./src-tauri/target/release/bundle/deb/${{ env.DEB_FILE_NAME }}
                      ./src-tauri/target/release/bundle/rpm/${{ env.RPM_FILE_NAME }}
                      ./src-tauri/target/release/bundle/appimage/${{ env.APPIMAGE_FILE_NAME }}
